name: et
description: Web developer and sleep enthusiast
author: Eric Trinh

# build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: null
permalink: /blog/:title
sass:
  style: :compressed

# can't change these; these are set by github pages
safe: true
lsi: false
